[[constraint]]
  name = "github.com/bradleyjkemp/memviz"
  branch = "master"

[[constraint]]
  name = "github.com/devopsfaith/krakend"
  version = "0.4.2"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
